//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmforwarding
    {
        public int id { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<int> siteId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> expiredate { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual sites sites { get; set; }
    }
}
