//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationConfigLog
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PcName { get; set; }
        public string SoftwareName { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
