//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class associations
    {
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<bool> valid { get; set; }
    }
}
