//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATSInfoTable
    {
        public int ID { get; set; }
        public int LoggerID { get; set; }
        public int b_a { get; set; }
        public int NetID { get; set; }
        public int CellID { get; set; }
        public long TxS { get; set; }
        public long FxS { get; set; }
        public long TxE { get; set; }
        public long FxE { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> SyncType { get; set; }
    }
}
