//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorInstrumentation
    {
        public int id { get; set; }
        public string siteIDDatagate { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> csq { get; set; }
        public Nullable<double> battery { get; set; }
        public Nullable<System.DateTime> lastCallIn { get; set; }
    }
}
