//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets
    {
        public int Id { get; set; }
        public string Details { get; set; }
        public System.DateTime BudgetDate { get; set; }
        public Nullable<int> IdRepairGuide { get; set; }
    
        public virtual RepairGuide RepairGuide { get; set; }
    }
}
