//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelationResults
    {
        public int Id { get; set; }
        public int RecID1 { get; set; }
        public int RecID2 { get; set; }
        public Nullable<double> Confidence { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<double> LengthUsed { get; set; }
        public Nullable<double> VelocityUsed { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<double> leakDistance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Method { get; set; }
    
        public virtual loggerrecordings loggerrecordings { get; set; }
        public virtual loggerrecordings loggerrecordings1 { get; set; }
    }
}
