//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credentials
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public byte[] PasswordSha256 { get; set; }
        public byte[] PasswordKey { get; set; }
        public bool State { get; set; }
        public bool EnableUpdatePassword { get; set; }
        public Nullable<System.DateTime> UpdatePasswordDateRequest { get; set; }
        public Nullable<int> IdProfile { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
