//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatFiles
    {
        public int ID { get; set; }
        public int LoggerID { get; set; }
        public bool PrimaryFile { get; set; }
        public string PreviousHash { get; set; }
        public Nullable<System.DateTime> PreviousHashDate { get; set; }
        public string LatestHash { get; set; }
        public Nullable<System.DateTime> LatestHashDate { get; set; }
        public string Location { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual loggers loggers { get; set; }
    }
}
