//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class gascalorificvalues
    {
        public int Id { get; set; }
        public System.DateTime applicable_at { get; set; }
        public System.DateTime applicable_for { get; set; }
        public string ldz { get; set; }
        public double calorificvalue { get; set; }
        public string quality_indicator { get; set; }
        public string substituted { get; set; }
        public System.DateTime created_date { get; set; }
        public System.DateTime generated_timestamp { get; set; }
    }
}
