//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNethubs
    {
        public int Id { get; set; }
        public string HubId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string SmsNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
