//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNetcustomers
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string AddressStreet { get; set; }
        public string AddressCity { get; set; }
        public string AddressAreacode { get; set; }
        public string AddressCountry { get; set; }
        public Nullable<double> HotTargetTemperature { get; set; }
        public Nullable<double> ColdTargetTemperature { get; set; }
        public Nullable<int> DurationMins { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
