//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNetlocations
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public string LocationName { get; set; }
        public string LocationType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ParentLocationId { get; set; }
    }
}
