//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNetalerts
    {
        public int Id { get; set; }
        public Nullable<int> TransmitterId { get; set; }
        public Nullable<int> ChannelNumber { get; set; }
        public string AlertType { get; set; }
        public string AlertCategory { get; set; }
        public Nullable<System.DateTime> AlertStartDate { get; set; }
        public Nullable<System.DateTime> AlertEndDate { get; set; }
        public Nullable<double> DataValue { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> LastNotificationDate { get; set; }
        public Nullable<bool> Acknowledged { get; set; }
        public string Notes { get; set; }
        public string AlertTypeKey { get; set; }
    }
}
