//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialComunicaciones
    {
        public int id { get; set; }
        public string SiteID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NumeroComms { get; set; }
        public string SMSNumber { get; set; }
        public Nullable<int> TotalComms { get; set; }
        public Nullable<int> RegistrationTime { get; set; }
    }
}
