//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class hubs
    {
        public int ID { get; set; }
        public string hubid { get; set; }
        public Nullable<System.DateTime> LastFileTime { get; set; }
        public Nullable<int> TimeError { get; set; }
        public Nullable<int> loggerid { get; set; }
        public string LastStatusFile { get; set; }
        public Nullable<System.DateTime> LastStatusFileDate { get; set; }
    }
}
