//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class installsite
    {
        public int Id { get; set; }
        public string SiteId { get; set; }
        public string Region { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public string SMPArea { get; set; }
        public string NodeRef { get; set; }
        public string FLOC { get; set; }
        public Nullable<int> AccountID { get; set; }
    }
}
