//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosST
    {
        public int id { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public string Supply { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CurrentStock { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<int> SquadID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
    }
}
