//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnstable
    {
        public int ID { get; set; }
        public string accountname { get; set; }
        public int siteid { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> leak { get; set; }
        public Nullable<int> noise { get; set; }
        public Nullable<int> spread { get; set; }
        public string siteaddress { get; set; }
        public Nullable<int> JobID { get; set; }
    }
}
