//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggerrecordings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loggerrecordings()
        {
            this.correlationAccountMeta = new HashSet<correlationAccountMeta>();
            this.CorrelationResults = new HashSet<CorrelationResults>();
            this.CorrelationResults1 = new HashSet<CorrelationResults>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public string SiteID { get; set; }
        public Nullable<System.DateTime> RST { get; set; }
        public Nullable<System.DateTime> RET { get; set; }
        public Nullable<int> RecordingType { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public Nullable<int> sampleratems { get; set; }
        public Nullable<int> Gain { get; set; }
        public Nullable<int> TimeSyncSpread { get; set; }
        public Nullable<long> PreSampleTimeRef { get; set; }
        public Nullable<long> PreSampleTimeValue { get; set; }
        public Nullable<long> PostSampleTimeRef { get; set; }
        public Nullable<long> PostSampleTimeValue { get; set; }
        public Nullable<int> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<correlationAccountMeta> correlationAccountMeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelationResults> CorrelationResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorrelationResults> CorrelationResults1 { get; set; }
    }
}
