//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class loggerconfigurationdata
    {
        public int ID { get; set; }
        public int LoggerID { get; set; }
        public int Address { get; set; }
        public byte[] data { get; set; }
        public byte[] validflags { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
    }
}
