//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookuptables
    {
        public int ID { get; set; }
        public Nullable<int> channelid { get; set; }
        public Nullable<double> valuein { get; set; }
        public Nullable<double> valueout { get; set; }
    
        public virtual channels channels { get; set; }
    }
}
