//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceJob
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InstallationReportId { get; set; }
        public string Reason { get; set; }
        public string TypeofMaintenance { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string Status { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> DateToBeCompleted { get; set; }
        public string AddiontionInfo { get; set; }
        public Nullable<int> AbortCode { get; set; }
        public string PerformedMaintenance { get; set; }
        public string DescriptionOfLocation { get; set; }
        public string MonitorSN { get; set; }
        public string FinalSignalStrength { get; set; }
        public string MainReason { get; set; }
        public string SecondaryReason { get; set; }
        public Nullable<double> Depth { get; set; }
        public Nullable<double> PipeSize { get; set; }
        public Nullable<double> DepthOffset { get; set; }
        public string PipeShape { get; set; }
        public Nullable<double> Velocity { get; set; }
        public Nullable<double> SpillLevel { get; set; }
        public Nullable<double> Flow { get; set; }
        public Nullable<bool> hasHealthAndSafety { get; set; }
        public Nullable<int> CompletedBy { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string CompletionComments { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> DateSignedOff { get; set; }
        public string DeclinedComments { get; set; }
        public Nullable<System.DateTime> DateDeclined { get; set; }
        public Nullable<int> RelocationInstallationID { get; set; }
        public Nullable<bool> ComplexTM { get; set; }
        public Nullable<bool> TMARequired { get; set; }
        public string SonicSensNumber { get; set; }
        public string AerialUsed { get; set; }
        public Nullable<System.DateTime> DateAssigned { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> maintenanceRequestID { get; set; }
        public string MonitorSMSNumber { get; set; }
        public Nullable<int> ComplexTMAID { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public Nullable<int> JobType { get; set; }
        public Nullable<int> OriginalId { get; set; }
    }
}
