//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceReportsServerStatus
    {
        public int ID { get; set; }
        public string ServerName { get; set; }
        public Nullable<bool> InProgress { get; set; }
        public Nullable<System.DateTime> InProgressStartDate { get; set; }
        public Nullable<System.DateTime> InProgressForceEndDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> ReportID { get; set; }
        public string LastError { get; set; }
        public Nullable<System.DateTime> LastErrorDate { get; set; }
    
        public virtual MaintenanceReportsServerStatus MaintenanceReportsServerStatus1 { get; set; }
        public virtual MaintenanceReportsServerStatus MaintenanceReportsServerStatus2 { get; set; }
    }
}
