//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceReports
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string ExportStatus { get; set; }
        public int ExportTypeID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> Expires { get; set; }
        public bool OnlyShowActiveSites { get; set; }
        public System.DateTime ScheduledReportDate { get; set; }
        public System.DateTime ReportStartDate { get; set; }
        public System.DateTime ReportEndDate { get; set; }
        public Nullable<System.DateTime> ReportRun { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IncludedList { get; set; }
        public string ScheduleRecurs { get; set; }
        public Nullable<int> ScheduleInterval { get; set; }
        public Nullable<int> ScheduleDay { get; set; }
        public string ScheduleWeekday { get; set; }
        public string ScheduleWeek { get; set; }
        public string ScheduledReportDetail { get; set; }
        public string Server { get; set; }
        public string DeliveryEmail { get; set; }
        public Nullable<int> ScheduledReportDetailKey { get; set; }
        public Nullable<int> ReportOptionsId { get; set; }
        public string FilterText { get; set; }
        public string ReportTitle { get; set; }
        public Nullable<System.DateTime> StartProcessingDate { get; set; }
        public int AttemptCount { get; set; }
        public string DeliveryOutputSettingName { get; set; }
        public string FilenameTemplate { get; set; }
    }
}
