//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGRequest
    {
        public string NGMReference { get; set; }
        public string JobType { get; set; }
        public string MeterPointReference { get; set; }
        public string ReadFrequency { get; set; }
        public string AlarmRequired { get; set; }
        public string AlarmHigh { get; set; }
        public string AlarmLow { get; set; }
        public string AlarmPeriod { get; set; }
        public string AlarmNotification { get; set; }
        public string AnnualQuantity { get; set; }
        public string SiteName { get; set; }
        public string SiteContact { get; set; }
        public string SiteContactNumber { get; set; }
        public string AccessInstructions { get; set; }
        public string SiteAddress { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string MeterSerialNumber { get; set; }
        public string MeterManufacturer { get; set; }
        public string MeterModel { get; set; }
        public string YearOfManufacture { get; set; }
        public string ConverterFitted { get; set; }
        public string AMRSerialNumber { get; set; }
        public string DMLoggerOnSite { get; set; }
        public string RequestNGMReference { get; set; }
        public string Comments { get; set; }
    }
}
