//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public string MessagesNotification { get; set; }
        public bool Acknowloedge { get; set; }
        public Nullable<int> IdProfile { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
