//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class openchannelconversion
    {
        public int ID { get; set; }
        public Nullable<int> OpenChannelHeaderID { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<double> Flow { get; set; }
    }
}
