//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class openchannelheader
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Geometry { get; set; }
        public Nullable<double> Slope { get; set; }
        public Nullable<double> Roughness { get; set; }
        public Nullable<int> Symmetry { get; set; }
        public Nullable<double> Sedimentmm { get; set; }
    }
}
