//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipeNetwork
    {
        public int ID { get; set; }
        public Nullable<int> SiteID1 { get; set; }
        public Nullable<int> SiteID2 { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<int> SpeedVelocityLookupId { get; set; }
        public Nullable<int> SegmentId { get; set; }
    }
}
