//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predictive
    {
        public int predictive_id { get; set; }
        public Nullable<System.DateTime> predictive_datetime { get; set; }
        public Nullable<double> predictive_max_value { get; set; }
        public Nullable<double> predictive_min_value { get; set; }
        public Nullable<double> predictive_avg_value { get; set; }
        public Nullable<double> predictive_ds_value { get; set; }
        public Nullable<int> predictive_type { get; set; }
        public Nullable<int> siteID { get; set; }
    }
}
