//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaisedAsLookup
    {
        public string RaisedAs { get; set; }
        public Nullable<double> RaisedAsESPB { get; set; }
        public Nullable<double> RaisedAsMld { get; set; }
    }
}
