//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recentsites
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> lastaccessdate { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual sites sites { get; set; }
        public virtual users users { get; set; }
    }
}
