//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int RoleId { get; set; }
        public string Description { get; set; }
        public Nullable<int> HWMOFlags { get; set; }
        public string LandingPage { get; set; }
        public Nullable<long> HWMOFlags64BIT { get; set; }
        public Nullable<bool> SuperRole { get; set; }
    }
}
