//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTLTransmitters
    {
        public int ID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public byte[] wi5cdata { get; set; }
        public string hubid { get; set; }
        public Nullable<int> TransmitterID { get; set; }
    }
}
