//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteLeakStatusHistory
    {
        public int ID { get; set; }
        public int SiteID { get; set; }
        public int LeakStatus { get; set; }
        public System.DateTime StatusChanged { get; set; }
    }
}
