//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCoordinates
    {
        public int ID { get; set; }
        public int SiteID { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public System.DateTime UtcDate { get; set; }
        public System.DateTime LocalDate { get; set; }
        public string EventType { get; set; }
        public System.DateTime LoggerLocalStartDate { get; set; }
    
        public virtual sites sites { get; set; }
    }
}
