//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteLoggerUserActions
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int UserAccountID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public int ActionType { get; set; }
        public Nullable<decimal> SiteLatitude { get; set; }
        public Nullable<decimal> SiteLongitude { get; set; }
        public string SiteNotes { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual accounts accounts { get; set; }
        public virtual accounts accounts1 { get; set; }
        public virtual loggers loggers { get; set; }
        public virtual sites sites { get; set; }
        public virtual users users { get; set; }
    }
}
