//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sites()
        {
            this.alarmforwarding = new HashSet<alarmforwarding>();
            this.datapoints = new HashSet<datapoints>();
            this.leakconfirmation = new HashSet<leakconfirmation>();
            this.leakconfirmationassociation = new HashSet<leakconfirmationassociation>();
            this.LeakDetectionOptions = new HashSet<LeakDetectionOptions>();
            this.LoggerAccessTechnology = new HashSet<LoggerAccessTechnology>();
            this.LoggerLevelAndSpread = new HashSet<LoggerLevelAndSpread>();
            this.loggermeterreadings = new HashSet<loggermeterreadings>();
            this.recentsites = new HashSet<recentsites>();
            this.SiteCoordinates = new HashSet<SiteCoordinates>();
            this.SiteLoggerUserActions = new HashSet<SiteLoggerUserActions>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DatagateID { get; set; }
        public Nullable<int> OwnerAccount { get; set; }
        public string SiteID { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string LatEast { get; set; }
        public string LongNorth { get; set; }
        public string HeightAOD { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Notes { get; set; }
        public string MaintenceNotes { get; set; }
        public Nullable<int> quietdays { get; set; }
        public Nullable<int> IntelligentAlarmStatusFlags { get; set; }
        public Nullable<int> PipeSize { get; set; }
        public Nullable<int> PipeMaterial { get; set; }
        public Nullable<bool> ValueLidModified { get; set; }
        public Nullable<int> ValveLidSize { get; set; }
        public Nullable<bool> maintenanceflag { get; set; }
        public Nullable<int> ChamberType { get; set; }
        public Nullable<int> QuietMins { get; set; }
        public Nullable<bool> IsQuiet { get; set; }
        public Nullable<bool> LeakState { get; set; }
        public Nullable<System.DateTime> SilenceAlarmDate { get; set; }
        public Nullable<System.DateTime> LastLeakDate { get; set; }
        public Nullable<double> Noise { get; set; }
        public Nullable<double> Spread { get; set; }
        public Nullable<bool> FlowLogger { get; set; }
        public Nullable<bool> PressureLogger { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<int> InstallationUserID { get; set; }
        public Nullable<bool> AlarmState { get; set; }
        public string InstalledBy { get; set; }
        public Nullable<System.DateTime> LastDataReceived { get; set; }
        public Nullable<System.DateTime> LastLoggerRemovedDate { get; set; }
        public Nullable<System.DateTime> LastNoiseOrSpreadChangedDate { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alarmforwarding> alarmforwarding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datapoints> datapoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leakconfirmation> leakconfirmation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<leakconfirmationassociation> leakconfirmationassociation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeakDetectionOptions> LeakDetectionOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoggerAccessTechnology> LoggerAccessTechnology { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoggerLevelAndSpread> LoggerLevelAndSpread { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<loggermeterreadings> loggermeterreadings { get; set; }
        public virtual loggers loggers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recentsites> recentsites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteCoordinates> SiteCoordinates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteLoggerUserActions> SiteLoggerUserActions { get; set; }
    }
}
