//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSFailures
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LastFailDateTime { get; set; }
        public int FailCount { get; set; }
        public int Status { get; set; }
    
        public virtual users users { get; set; }
    }
}
