//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class steptesthistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public string SiteIdOld { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
    }
}
