//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class steptestcredits
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CreditsRemaining { get; set; }
        public string AccountAdmin { get; set; }
        public string AccountAdminEmail { get; set; }
    }
}
