//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplieMobile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Stock { get; set; }
        public int MinimumStock { get; set; }
        public int IdSupplie { get; set; }
        public int IdSquad { get; set; }
    
        public virtual Squad Squad { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
