//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasPreventivas
    {
        public int id { get; set; }
        public string cliente { get; set; }
        public string sucursal { get; set; }
        public string tasktype { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string currentstatus { get; set; }
    }
}
