//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalServices
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datetimeIn { get; set; }
        public Nullable<System.DateTime> datetimeOut { get; set; }
        public string serviceReference { get; set; }
        public string suppliesUsed { get; set; }
        public string diagnosticDevice { get; set; }
        public string idFieldBeat { get; set; }
    }
}
