//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitslookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unitslookup()
        {
            this.AccountLeakOptions = new HashSet<AccountLeakOptions>();
            this.UserUnitLookup = new HashSet<UserUnitLookup>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public string Units { get; set; }
        public Nullable<double> Multiplier { get; set; }
        public Nullable<double> Offset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLeakOptions> AccountLeakOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUnitLookup> UserUnitLookup { get; set; }
    }
}
