//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class witsendpoints
    {
        public int ID { get; set; }
        public Nullable<bool> enabled { get; set; }
        public Nullable<int> accountID { get; set; }
        public string serveraddress { get; set; }
        public Nullable<int> serverport { get; set; }
        public Nullable<int> serverdnp3address { get; set; }
        public Nullable<int> serverconnecttimeout { get; set; }
        public Nullable<int> servercommstimeout { get; set; }
        public Nullable<long> lastmessageid { get; set; }
        public Nullable<System.DateTime> lastexportdate { get; set; }
        public Nullable<int> lastexportedsiteid { get; set; }
        public Nullable<int> status { get; set; }
    }
}
