//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class witssitedetails
    {
        public int ID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> dnp3id { get; set; }
        public string Witstring0 { get; set; }
        public string Witstring1 { get; set; }
        public string Witstring2 { get; set; }
        public string Witstring3 { get; set; }
        public string Witstring4 { get; set; }
        public string Witstring5 { get; set; }
        public string Witstring6 { get; set; }
        public string Witstring7 { get; set; }
    }
}
