//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleCargaDatosDNK.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class WWAlarmSettingsTable
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> AmberEventDurationSeconds { get; set; }
        public Nullable<int> RedEventDurationSeconds { get; set; }
        public Nullable<int> LowCSQThreshold { get; set; }
        public Nullable<int> AlarmDaysThreshold { get; set; }
    }
}
